import { Trade } from "@/types/trading";

export const INITIAL_CLOSED_TRADES: Trade[] = [
  {
    id: "TR-801",
    symbol: "EUR/USD",
    name: "Euro / US Dollar",
    side: "BUY",
    amount: 1.0,
    entryPrice: 1.0832,
    exitPrice: 1.085,
    pnl: 0.18,
    pnlPercent: 18.0,
    openTime: new Date(Date.now() - 42 * 60000).toISOString(),
    closeTime: new Date(Date.now() - 36 * 60000).toISOString(),
    duration: "6m 12s",
    closeReason: "TAKE_PROFIT",
    isWin: true,
    reasoning: {
      tradeId: "AI-104921",
      symbol: "EUR/USD",
      side: "BUY",
      timeframe: "M5",
      confidence: 84,
      strategyModel: "AlphaTrend Neural Scalper",
      strategyVersion: "v2.8.4-Quant",
      indicators: {
        rsi: 41.5,
        emaTrend: "EMA(9) crossed above EMA(21) on 5m timeframe with bullish slope",
        macdStatus: "Positive histogram expansion (+0.0024), signal line cross confirmed",
        volatilityAtr: "ATR(14) 0.0008, spread 0.8 pips",
        supportResistance: "Liquidity sweep below S1 with buyer absorption",
        orderFlow: "64% bid-side imbalance with delta spike",
      },
      rationale:
        "Algorithmic engine detected a high-probability liquidity reclaim on EUR/USD. Mean-reversion trigger confirmed by RSI oversold divergence.",
      stopTargetRationale: "Target 1.0850 (+18 pips) / Stop 1.0821 (-11 pips)",
      riskRewardRatio: "1:1.64",
      stopLossPrice: 1.0821,
      takeProfitPrice: 1.085,
      timestamp: new Date(Date.now() - 42 * 60000).toISOString(),
      latencyMs: 14,
    },
  },
  {
    id: "TR-802",
    symbol: "XAU/USD",
    name: "Gold / US Dollar",
    side: "SELL",
    amount: 1.0,
    entryPrice: 2688.4,
    exitPrice: 2689.5,
    pnl: -0.11,
    pnlPercent: -11.0,
    openTime: new Date(Date.now() - 31 * 60000).toISOString(),
    closeTime: new Date(Date.now() - 27 * 60000).toISOString(),
    duration: "4m 18s",
    closeReason: "STOP_LOSS",
    isWin: false,
    reasoning: {
      tradeId: "AI-104928",
      symbol: "XAU/USD",
      side: "SELL",
      timeframe: "M5",
      confidence: 79,
      strategyModel: "AlphaTrend Neural Scalper",
      strategyVersion: "v2.8.4-Quant",
      indicators: {
        rsi: 68.2,
        emaTrend: "EMA(9) test of EMA(21) downward slope",
        macdStatus: "Bearish divergence on 5m",
        volatilityAtr: "ATR(14) 1.82, spread 2.5 pips",
        supportResistance: "Rejection test at R1 resistance zone",
        orderFlow: "Passive asks present at 2689.00",
      },
      rationale:
        "Momentum breakdown attempt stalled as sudden USD safe-haven headline caused stop-loss trigger. Risk engine liquidated position strictly according to bracket.",
      stopTargetRationale: "Target 2682.00 / Stop 2689.50",
      riskRewardRatio: "1:1.50",
      stopLossPrice: 2689.5,
      takeProfitPrice: 2682.0,
      timestamp: new Date(Date.now() - 31 * 60000).toISOString(),
      latencyMs: 18,
    },
  },
  {
    id: "TR-803",
    symbol: "GBP/USD",
    name: "British Pound / US Dollar",
    side: "BUY",
    amount: 1.0,
    entryPrice: 1.3105,
    exitPrice: 1.3126,
    pnl: 0.21,
    pnlPercent: 21.0,
    openTime: new Date(Date.now() - 25 * 60000).toISOString(),
    closeTime: new Date(Date.now() - 19 * 60000).toISOString(),
    duration: "6m 04s",
    closeReason: "TAKE_PROFIT",
    isWin: true,
    reasoning: {
      tradeId: "AI-104933",
      symbol: "GBP/USD",
      side: "BUY",
      timeframe: "M15",
      confidence: 88,
      strategyModel: "AlphaTrend Neural Scalper",
      strategyVersion: "v2.8.4-Quant",
      indicators: {
        rsi: 48.0,
        emaTrend: "Bullish golden cross 15m",
        macdStatus: "Histogram expansion in positive quadrant",
        volatilityAtr: "ATR 0.0011, spread 1.1 pips",
        supportResistance: "Support bounce off London opening range high",
        orderFlow: "Aggressive market buy orders absorbing liquidity",
      },
      rationale:
        "London session momentum continuation. Algorithmic volume profiling detected institutional accumulation above 1.3100 psychological level.",
      stopTargetRationale: "Target 1.3126 / Stop 1.3092",
      riskRewardRatio: "1:1.62",
      stopLossPrice: 1.3092,
      takeProfitPrice: 1.3126,
      timestamp: new Date(Date.now() - 25 * 60000).toISOString(),
      latencyMs: 12,
    },
  },
  {
    id: "TR-804",
    symbol: "BTC/USD",
    name: "Bitcoin / US Dollar",
    side: "BUY",
    amount: 1.0,
    entryPrice: 63720.0,
    exitPrice: 63980.0,
    pnl: 0.26,
    pnlPercent: 26.0,
    openTime: new Date(Date.now() - 17 * 60000).toISOString(),
    closeTime: new Date(Date.now() - 11 * 60000).toISOString(),
    duration: "5m 48s",
    closeReason: "TAKE_PROFIT",
    isWin: true,
    reasoning: {
      tradeId: "AI-104940",
      symbol: "BTC/USD",
      side: "BUY",
      timeframe: "M5",
      confidence: 86,
      strategyModel: "Crypto Momentum Quant v3.1",
      strategyVersion: "v3.1.0-Crypto",
      indicators: {
        rsi: 39.4,
        emaTrend: "Bullish reversal candle through EMA(20)",
        macdStatus: "MACD crossing signal line from below",
        volatilityAtr: "ATR 85.0, spread 8 pips",
        supportResistance: "Weekly VWAP support reclamation",
        orderFlow: "Coinbase delta cumulative volume index rising",
      },
      rationale:
        "Reclamation of key daily VWAP after minor liquidity dip. Strategy executed buy on structural engulfing bar.",
      stopTargetRationale: "Target 63980 / Stop 63560",
      riskRewardRatio: "1:1.63",
      stopLossPrice: 63560.0,
      takeProfitPrice: 63980.0,
      timestamp: new Date(Date.now() - 17 * 60000).toISOString(),
      latencyMs: 16,
    },
  },
  {
    id: "TR-805",
    symbol: "WTI/USD",
    name: "Crude Oil / US Dollar",
    side: "BUY",
    amount: 1.0,
    entryPrice: 71.3,
    exitPrice: 71.48,
    pnl: 0.18,
    pnlPercent: 18.0,
    openTime: new Date(Date.now() - 10 * 60000).toISOString(),
    closeTime: new Date(Date.now() - 4 * 60000).toISOString(),
    duration: "5m 22s",
    closeReason: "TAKE_PROFIT",
    isWin: true,
    reasoning: {
      tradeId: "AI-104948",
      symbol: "WTI/USD",
      side: "BUY",
      timeframe: "M5",
      confidence: 82,
      strategyModel: "Commodity Trend Follower",
      strategyVersion: "v2.1.0-Comm",
      indicators: {
        rsi: 54.2,
        emaTrend: "Aligned above 20 and 50 period moving averages",
        macdStatus: "Sustained positive MACD histogram",
        volatilityAtr: "ATR 0.22, spread 0.04",
        supportResistance: "Break of Asian session high",
        orderFlow: "Strong prompt futures bids",
      },
      rationale:
        "Trend continuation play matching positive energy inventory sentiment. Clean breakout followed by momentum surge.",
      stopTargetRationale: "Target 71.48 / Stop 71.18",
      riskRewardRatio: "1:1.50",
      stopLossPrice: 71.18,
      takeProfitPrice: 71.48,
      timestamp: new Date(Date.now() - 10 * 60000).toISOString(),
      latencyMs: 15,
    },
  },
  {
    id: "TR-806",
    symbol: "USD/JPY",
    name: "US Dollar / Japanese Yen",
    side: "SELL",
    amount: 1.0,
    entryPrice: 144.55,
    exitPrice: 144.68,
    pnl: -0.13,
    pnlPercent: -13.0,
    openTime: new Date(Date.now() - 8 * 60000).toISOString(),
    closeTime: new Date(Date.now() - 3 * 60000).toISOString(),
    duration: "4m 50s",
    closeReason: "STOP_LOSS",
    isWin: false,
    reasoning: {
      tradeId: "AI-104952",
      symbol: "USD/JPY",
      side: "SELL",
      timeframe: "M5",
      confidence: 76,
      strategyModel: "AlphaTrend Neural Scalper",
      strategyVersion: "v2.8.4-Quant",
      indicators: {
        rsi: 71.0,
        emaTrend: "Testing resistance band",
        macdStatus: "Flattening momentum",
        volatilityAtr: "ATR 0.14, spread 0.9 pips",
        supportResistance: "Major psychological round number 144.50",
        orderFlow: "Limit sell wall in place",
      },
      rationale:
        "Attempted short on overbought RSI failed when unexpected Treasury yield spike drove Yen cross higher. Protected by hard stop.",
      stopTargetRationale: "Target 144.32 / Stop 144.68",
      riskRewardRatio: "1:1.77",
      stopLossPrice: 144.68,
      takeProfitPrice: 144.32,
      timestamp: new Date(Date.now() - 8 * 60000).toISOString(),
      latencyMs: 19,
    },
  },
  {
    id: "TR-807",
    symbol: "EUR/USD",
    name: "Euro / US Dollar",
    side: "BUY",
    amount: 1.0,
    entryPrice: 1.0838,
    exitPrice: 1.0857,
    pnl: 0.19,
    pnlPercent: 19.0,
    openTime: new Date(Date.now() - 3 * 60000).toISOString(),
    closeTime: new Date(Date.now() - 45000).toISOString(),
    duration: "2m 15s",
    closeReason: "TAKE_PROFIT",
    isWin: true,
    reasoning: {
      tradeId: "AI-104961",
      symbol: "EUR/USD",
      side: "BUY",
      timeframe: "M5",
      confidence: 89,
      strategyModel: "AlphaTrend Neural Scalper",
      strategyVersion: "v2.8.4-Quant",
      indicators: {
        rsi: 58.2,
        emaTrend: "Clean upward channel following retest",
        macdStatus: "Bullish divergence continuation",
        volatilityAtr: "ATR 0.0007, spread 0.8 pips",
        supportResistance: "Retest and bounce of prior swing high",
        orderFlow: "Strong institutional bid tape",
      },
      rationale:
        "Pullback buy setup on trendline confluence. Scalping engine executed precision entry with instant positive drift.",
      stopTargetRationale: "Target 1.0857 / Stop 1.0826",
      riskRewardRatio: "1:1.58",
      stopLossPrice: 1.0826,
      takeProfitPrice: 1.0857,
      timestamp: new Date(Date.now() - 3 * 60000).toISOString(),
      latencyMs: 11,
    },
  },
];
